version: "3"

services:
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "3000:80"
    networks:
      - movies-network
    depends_on:
      - movies-api
      - movies-ui

  movies-api:
    build:
      context: ./movies-back-v1
    env_file: .env
    environment:
      PGUSER: $POSTGRES_USER
      PGPASSWORD: $POSTGRES_PASSWORD
      PGDATABASE: $POSTGRES_DB
      PGHOST: db
      PGPORT: 5432
    volumes:
      - ./movies-back-v1:/app
    networks:
      - movies-network
    depends_on:
      - db

  db:
    image: postgres:10.3-alpine
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/db-data
    networks:
      - movies-network

  movies-ui:
    build:
      context: ./movies-front
    volumes:
      - ./movies-front:/app
    stdin_open: true
    networks:
      - movies-network

volumes:
  db-data:
networks:
  movies-network:
